package Lex;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 31;
  public static final int GTEQ = 25;
  public static final int STRING_LITERAL = 17;
  public static final int LBRACKET = 38;
  public static final int LTEQ = 24;
  public static final int LPAREN = 34;
  public static final int CONTINUE = 12;
  public static final int INT = 4;
  public static final int FOR = 9;
  public static final int MINUS = 29;
  public static final int RPAREN = 35;
  public static final int OROR = 27;
  public static final int BOOLEAN_LITERAL = 16;
  public static final int NOT = 19;
  public static final int SEMICOLON = 32;
  public static final int LT = 22;
  public static final int COMMA = 33;
  public static final int ANDAND = 26;
  public static final int PLUS = 28;
  public static final int MULTIPLY = 30;
  public static final int IF = 7;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 13;
  public static final int RBRACKET = 39;
  public static final int error = 1;
  public static final int EQEQ = 20;
  public static final int BREAK = 11;
  public static final int VOID = 2;
  public static final int EQ = 18;
  public static final int LBRACE = 36;
  public static final int ELSE = 8;
  public static final int WHILE = 10;
  public static final int FLOAT = 5;
  public static final int RBRACE = 37;
  public static final int FLOAT_LITERAL = 15;
  public static final int GT = 23;
  public static final int NOTEQ = 21;
  public static final int INTEGER_LITERAL = 14;
  public static final String[] terminalNames = new String[] {
          "EOF",
          "error",
          "VOID",
          "BOOLEAN",
          "INT",
          "FLOAT",
          "ID",
          "IF",
          "ELSE",
          "FOR",
          "WHILE",
          "BREAK",
          "CONTINUE",
          "RETURN",
          "INTEGER_LITERAL",
          "FLOAT_LITERAL",
          "BOOLEAN_LITERAL",
          "STRING_LITERAL",
          "EQ",
          "NOT",
          "EQEQ",
          "NOTEQ",
          "LT",
          "GT",
          "LTEQ",
          "GTEQ",
          "ANDAND",
          "OROR",
          "PLUS",
          "MINUS",
          "MULTIPLY",
          "DIVIDE",
          "SEMICOLON",
          "COMMA",
          "LPAREN",
          "RPAREN",
          "LBRACE",
          "RBRACE",
          "LBRACKET",
          "RBRACKET"
  };
}

